Add warning info for if the sample output cannot be download for Part 2

diff --git a/script/new b/script/new
--- a/script/new
+++ b/script/new
@@ -36,6 +36,12 @@ perl -ne '$/ = undef; print "$1" and exit 0 if /<pre><code>(.+?)<\/code><\/pre>/
 perl -ne '$/ = undef; print "$1" and exit 0 if /<code><em>(.+?)<\/em><\/code>/s' "${NEW_DIR}/story.html" > "${NEW_DIR}/sample_output.pt1.txt"
 perl -ne '$/ = undef; print "$1" and exit 0 if /<h2 id="part2">.+?<code><em>(.+?)<\/em><\/code>/s' "${NEW_DIR}/story.html" > "${NEW_DIR}/sample_output.pt2.txt"
 
+SAMPLE_OUTPUT_PART2_FILESIZE=$(wc -c "${NEW_DIR}/sample_output.pt2.txt" | awk '{print $1}')
+if [[ "$SAMPLE_OUTPUT_PART2_FILESIZE" -eq 0 ]]; then
+  echo "⚠️ WARNING: Unable to download the sample output for Part 2 until you've completed Part 1." >&2
+  echo "ℹ️ You can safely run this script again after submitting your answer to Part 1!" >&2
+fi
+
 # Remove the story HTML file
 rm "${NEW_DIR}/story.html"
 
